using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace ExchangeOffice.BLL
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------



    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class dsKurs
    {

        private dsKursKursZbir[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KursZbir", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dsKursKursZbir[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class dsKursKursZbir
    {

        private double rBrField;

        private bool rBrFieldSpecified;

        private System.DateTime datumField;

        private bool datumFieldSpecified;

        private double valutaField;

        private bool valutaFieldSpecified;

        private string oznakaField;

        private string drzavaField;

        private double nominField;

        private bool nominFieldSpecified;

        private double sredenField;

        private bool sredenFieldSpecified;

        private string drzavaAngField;

        private string drzavaAlField;

        private string nazivMakField;

        private string nazivAngField;

        private string valutaNaziv_ALField;

        private System.DateTime datum_fField;

        private bool datum_fFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double RBr
        {
            get
            {
                return this.rBrField;
            }
            set
            {
                this.rBrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RBrSpecified
        {
            get
            {
                return this.rBrFieldSpecified;
            }
            set
            {
                this.rBrFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumSpecified
        {
            get
            {
                return this.datumFieldSpecified;
            }
            set
            {
                this.datumFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Valuta
        {
            get
            {
                return this.valutaField;
            }
            set
            {
                this.valutaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValutaSpecified
        {
            get
            {
                return this.valutaFieldSpecified;
            }
            set
            {
                this.valutaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Oznaka
        {
            get
            {
                return this.oznakaField;
            }
            set
            {
                this.oznakaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Drzava
        {
            get
            {
                return this.drzavaField;
            }
            set
            {
                this.drzavaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Nomin
        {
            get
            {
                return this.nominField;
            }
            set
            {
                this.nominField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NominSpecified
        {
            get
            {
                return this.nominFieldSpecified;
            }
            set
            {
                this.nominFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Sreden
        {
            get
            {
                return this.sredenField;
            }
            set
            {
                this.sredenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SredenSpecified
        {
            get
            {
                return this.sredenFieldSpecified;
            }
            set
            {
                this.sredenFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DrzavaAng
        {
            get
            {
                return this.drzavaAngField;
            }
            set
            {
                this.drzavaAngField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DrzavaAl
        {
            get
            {
                return this.drzavaAlField;
            }
            set
            {
                this.drzavaAlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NazivMak
        {
            get
            {
                return this.nazivMakField;
            }
            set
            {
                this.nazivMakField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NazivAng
        {
            get
            {
                return this.nazivAngField;
            }
            set
            {
                this.nazivAngField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValutaNaziv_AL
        {
            get
            {
                return this.valutaNaziv_ALField;
            }
            set
            {
                this.valutaNaziv_ALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Datum_f
        {
            get
            {
                return this.datum_fField;
            }
            set
            {
                this.datum_fField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Datum_fSpecified
        {
            get
            {
                return this.datum_fFieldSpecified;
            }
            set
            {
                this.datum_fFieldSpecified = value;
            }
        }
    }
}


